###
# @name userRegister
POST http://localhost:4200/api/user/register HTTP/1.1
content-type: application/json

{
    "email": "demo@demo.com",
    "password": "demo@demo.com"
}

###
# @name userLogin
POST http://localhost:4200/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "demo@demo.com",
    "password": "demo@demo.com"
}

###
# @name userLogin2FA
POST http://localhost:4200/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "demo@demo.com",
    "password": "demo@demo.com",
    "tfaToken": "000000"
}

###
# @name userLogout
POST http://localhost:4200/api/user/logout HTTP/1.1
content-type: application/json

###
# @name userIsLoggedIn
GET http://localhost:4200/api/user/isLoggedIn HTTP/1.1
