language: node_js

node_js:
 - "12.18.3"

branches:
  only:
    - dev

notifications:
  email: false

addons:
  chrome: stable

cache:
  npm: true
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - name: test-headless
      node_js: "12.18.3"
      script: npm run test-headless
    - name: e2e
      node_js: "12.18.3"
      script: npm run e2e

script:
  - npm run build:ssr